# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: NPM Publish

on:
  push:
    tags:
      - '**'

jobs:

  publish-npm:

    name: Publish to NPM

    if: github.repository_owner == 'coajs'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/

      - name: Build
        run: |
          git config --global user.email "spryti@163.com"
          git config --global user.name "AexBot"
          npm version ${{ github.ref }}
          npm run build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.AEX_NPM_TOKEN }}
        run: |
          cd dist
          npm publish
